[package]
name = "nlprule"
version = "0.1.0"
authors = ["Benjamin Minixhofer <bminixhofer@gmail.com>"]
edition = "2018"

[lib]
name = "nlprule"
crate-type = ["cdylib"]

[dependencies]
bincode = "1.3"
reqwest = { version = "0.10", features = ["blocking"]}
flate2 = "1"
directories = "3"
nlprule_core = { path = "../../nlprule" }

[dependencies.pyo3]
version = "0.13"
features = ["extension-module"]
